### ISSUE TITLE
The url get code is 404

### ISSUE THREAD

**Issue by linhpn96** [kashishgupta1990/gmail-node#5]
the url in command click to get code is 404.

**Comment by kashishgupta1990** [comment]
@psssssa  - Can you please elaborate the issue. Steps to reproduce.

Thanks

**Comment by kashishgupta1990** [comment]
@psssssa - Please generate the `clientSecret ` via steps given on README file.

**Comment by linhpn96** [comment]
i do that. but it not work

**Comment by linhpn96** [comment]
clientSecret = {
    installed: {
        client_id: "secret.apps.googleusercontent.com",
        project_id: "mail-secret",
        auth_uri: "https://accounts.google.com/o/oauth2/auth",
        token_uri: "https://accounts.google.com/o/oauth2/token",
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
        client_secret: "secret-Mff9ZtQk1wc1",
        redirect_uris: [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost:3000"
        ]
    }

**Comment by linhpn96** [comment]
that true

**Comment by linhpn96** [comment]
sorry my mistake
